### ISSUE TITLE
Security Alert addressable

### ISSUE THREAD

**Issue by eacton** [SFU-Lee-Lab/Lee_Lab_Webpage#1]
Hi @ewanbrinkman! Another security alert has popped up for the current version of addressable. Would you mind taking a look when you get a chance?  Thanks!

**Comment by ewanbrinkman** [comment]
Thank you for letting me know @eacton! I updated addressable, so hopefully that fixes it. Let me know if there is still a problem.

**Comment by eacton** [comment]
Great! Thanks, @ewanbrinkman!
